<a href="https://colab.research.google.com/github/bharathrockstar813-byte/e-commerce-/blob/main/dataframes2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
df = pd.read_excel("/content/drive/MyDrive/data cleaing/student_dataset_20rows.xlsx")
print(df)

    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
3          104    Kiran   21      Data Science     98    Bangalore
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
8          109    Pooja   20            Python     95        Vizag
9          110   Vikram   20               SQL     72     Tirupati
10         111    Divya   23     Deep Learning     94     Warangal
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
13         114   Nikhil   22     Deep Learning     99       Kadapa
14         115    Meena   23                AI     81      Kurnool
15         116      Sai   25            Pandas     97       Ongole
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad

In [12]:
df

    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
3          104    Kiran   21      Data Science     98    Bangalore
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
8          109    Pooja   20            Python     95        Vizag
9          110   Vikram   20               SQL     72     Tirupati
10         111    Divya   23     Deep Learning     94     Warangal
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
13         114   Nikhil   22     Deep Learning     99       Kadapa
14         115    Meena   23                AI     81      Kurnool
15         116      Sai   25            Pandas     97       Ongole
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad

In [25]:
df.iloc[0]

Student_ID       101
Name             Ram
Age               25
Course        Pandas
Marks             90
Name: 0, dtype: object

In [28]:
df

    Student_ID     Name  Age            Course  Marks
0          101      Ram   25            Pandas     90
1          102     Ravi   23             NumPy     81
2          103     Sita   21            Python     80
3          104    Kiran   21      Data Science     98
4          105      Anu   20            Pandas     70
5          106    Rahul   22               SQL     82
6          107    Sneha   25     Deep Learning     79
7          108    Arjun   22  Machine Learning     70
8          109    Pooja   20            Python     95
9          110   Vikram   20               SQL     72
10         111    Divya   23     Deep Learning     94
11         112     Ajay   21            Python     84
12         113  Keerthi   21             NumPy     74
13         114   Nikhil   22     Deep Learning     99
14         115    Meena   23                AI     81
15         116      Sai   25            Pandas     97
16         117  Lavanya   20                AI     72
17         118    Rohit   23            Python     70
18         119     Teja   25  Machine Learning     90
19         120    Priya   22               SQL     78

In [27]:
df.columns

Index(['Student_ID', 'Name', 'Age', 'Course', 'Marks'], dtype='object')

In [30]:
#selecting rows using
#ioloc = intger location
df.iloc[0]

Student_ID       101
Name             Ram
Age               25
Course        Pandas
Marks             90
Name: 0, dtype: object

In [31]:
#selecting specific rown and columns
#df.iloc[rowselcton, comnsselection]
df.iloc[0:3,0:3]

   Student_ID  Name  Age
0         101   Ram   25
1         102  Ravi   23
2         103  Sita   21

In [32]:
df.iloc[[0,1,2,3]]

   Student_ID   Name  Age        Course  Marks
0         101    Ram   25        Pandas     90
1         102   Ravi   23         NumPy     81
2         103   Sita   21        Python     80
3         104  Kiran   21  Data Science     98

In [33]:
df.iloc[[0,1]]

   Student_ID  Name  Age  Course  Marks
0         101   Ram   25  Pandas     90
1         102  Ravi   23   NumPy     81

In [34]:
df.iloc[:,1]

0         Ram
1        Ravi
2        Sita
3       Kiran
4         Anu
5       Rahul
6       Sneha
7       Arjun
8       Pooja
9      Vikram
10      Divya
11       Ajay
12    Keerthi
13     Nikhil
14      Meena
15        Sai
16    Lavanya
17      Rohit
18       Teja
19      Priya
Name: Name, dtype: object

In [35]:
df.loc[0:2]

   Student_ID  Name  Age  Course  Marks
0         101   Ram   25  Pandas     90
1         102  Ravi   23   NumPy     81
2         103  Sita   21  Python     80

In [36]:
df.loc[:,"Name"]

0         Ram
1        Ravi
2        Sita
3       Kiran
4         Anu
5       Rahul
6       Sneha
7       Arjun
8       Pooja
9      Vikram
10      Divya
11       Ajay
12    Keerthi
13     Nikhil
14      Meena
15        Sai
16    Lavanya
17      Rohit
18       Teja
19      Priya
Name: Name, dtype: object

In [ ]:
df.loc[5:8, ["Name", "Age"," City"]]

In [51]:
#tasks1
df.iloc[:,1]

0         Ram
1        Ravi
2        Sita
3       Kiran
4         Anu
5       Rahul
6       Sneha
7       Arjun
8       Pooja
9      Vikram
10      Divya
11       Ajay
12    Keerthi
13     Nikhil
14      Meena
15        Sai
16    Lavanya
17      Rohit
18       Teja
19      Priya
Name: Name, dtype: object

In [52]:
df.loc[:,"Name"]

0         Ram
1        Ravi
2        Sita
3       Kiran
4         Anu
5       Rahul
6       Sneha
7       Arjun
8       Pooja
9      Vikram
10      Divya
11       Ajay
12    Keerthi
13     Nikhil
14      Meena
15        Sai
16    Lavanya
17      Rohit
18       Teja
19      Priya
Name: Name, dtype: object

In [54]:
df.columns

Index(['Student_ID', 'Name', 'Age', 'Course', 'Marks'], dtype='object')

In [ ]:
df.loc[:, ["Nmae", "City"]]

In [57]:
df.iloc[[0,1,2],:]

   Student_ID  Name  Age  Course  Marks
0         101   Ram   25  Pandas     90
1         102  Ravi   23   NumPy     81
2         103  Sita   21  Python     80

In [58]:
df

    Student_ID     Name  Age            Course  Marks
0          101      Ram   25            Pandas     90
1          102     Ravi   23             NumPy     81
2          103     Sita   21            Python     80
3          104    Kiran   21      Data Science     98
4          105      Anu   20            Pandas     70
5          106    Rahul   22               SQL     82
6          107    Sneha   25     Deep Learning     79
7          108    Arjun   22  Machine Learning     70
8          109    Pooja   20            Python     95
9          110   Vikram   20               SQL     72
10         111    Divya   23     Deep Learning     94
11         112     Ajay   21            Python     84
12         113  Keerthi   21             NumPy     74
13         114   Nikhil   22     Deep Learning     99
14         115    Meena   23                AI     81
15         116      Sai   25            Pandas     97
16         117  Lavanya   20                AI     72
17         118    Rohit   23            Python     70
18         119     Teja   25  Machine Learning     90
19         120    Priya   22               SQL     78

In [60]:
df.sort_values(by="Marks") # ascending

    Student_ID     Name  Age            Course  Marks
7          108    Arjun   22  Machine Learning     70
4          105      Anu   20            Pandas     70
17         118    Rohit   23            Python     70
9          110   Vikram   20               SQL     72
16         117  Lavanya   20                AI     72
12         113  Keerthi   21             NumPy     74
19         120    Priya   22               SQL     78
6          107    Sneha   25     Deep Learning     79
2          103     Sita   21            Python     80
1          102     Ravi   23             NumPy     81
14         115    Meena   23                AI     81
5          106    Rahul   22               SQL     82
11         112     Ajay   21            Python     84
18         119     Teja   25  Machine Learning     90
0          101      Ram   25            Pandas     90
10         111    Divya   23     Deep Learning     94
8          109    Pooja   20            Python     95
15         116      Sai   25            Pandas     97
3          104    Kiran   21      Data Science     98
13         114   Nikhil   22     Deep Learning     99

In [61]:
df.sort_values(
    by="Marks", ascending=False
)

    Student_ID     Name  Age            Course  Marks
13         114   Nikhil   22     Deep Learning     99
3          104    Kiran   21      Data Science     98
15         116      Sai   25            Pandas     97
8          109    Pooja   20            Python     95
10         111    Divya   23     Deep Learning     94
18         119     Teja   25  Machine Learning     90
0          101      Ram   25            Pandas     90
11         112     Ajay   21            Python     84
5          106    Rahul   22               SQL     82
1          102     Ravi   23             NumPy     81
14         115    Meena   23                AI     81
2          103     Sita   21            Python     80
6          107    Sneha   25     Deep Learning     79
19         120    Priya   22               SQL     78
12         113  Keerthi   21             NumPy     74
9          110   Vikram   20               SQL     72
16         117  Lavanya   20                AI     72
7          108    Arjun   22  Machine Learning     70
4          105      Anu   20            Pandas     70
17         118    Rohit   23            Python     70

In [64]:
df.sort_values(by="city")

KeyError: 'city'

In [ ]:
df.sort_values(by=["city",])