<a href="https://colab.research.google.com/github/bharathrockstar813-byte/e-commerce-/blob/main/knnregession16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score

In [4]:
df=pd.read_csv("/content/drive/MyDrive/data cleaing/Copy of knnregression.csv")

In [5]:
df

     House_Size_sqft  Bedrooms  Age_of_House  Distance_to_City_km  Price_Lakhs
0               3874         7             8                 15.2        232.2
1               2338         4            11                 21.7        116.0
2               3871         7            21                 24.3        202.2
3               2215         4            10                  1.6        132.8
4               3447         6            15                 15.7        182.5
..               ...       ...           ...                  ...          ...
495             2084         6             6                 22.3        119.0
496             2636         5            27                  3.9        143.7
497             1061         1             3                 11.5         47.4
498             2575         5             6                 21.4        133.3
499             1580         3            21                 11.2         68.8

[500 rows x 5 columns]

In [6]:
df.head()

   House_Size_sqft  Bedrooms  Age_of_House  Distance_to_City_km  Price_Lakhs
0             3874         7             8                 15.2        232.2
1             2338         4            11                 21.7        116.0
2             3871         7            21                 24.3        202.2
3             2215         4            10                  1.6        132.8
4             3447         6            15                 15.7        182.5

In [7]:
df.isnull().sum()

House_Size_sqft        0
Bedrooms               0
Age_of_House           0
Distance_to_City_km    0
Price_Lakhs            0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.describe()

,House_Size_sqft,Bedrooms,Age_of_House,Distance_to_City_km,Price_Lakhs
count,500.000000,500.000000,500.000000,500.000000,500.000000
mean,2363.158000,4.328000,15.504000,13.300400,126.244200
std,963.240532,1.879223,9.020683,7.160085,64.441314
min,710.000000,1.000000,1.000000,0.500000,20.000000
25%,1569.750000,3.000000,8.000000,7.375000,71.200000
50%,2407.500000,4.000000,16.000000,13.900000,126.100000
75%,3200.500000,6.000000,23.000000,19.525000,181.750000
max,3998.000000,8.000000,30.000000,25.000000,256.300000

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   House_Size_sqft      500 non-null    int64
 1   Bedrooms             500 non-null    int64
 2   Age_of_House         500 non-null    int64
 3   Distance_to_City_km  500 non-null    float64
 4   Price_Lakhs          500 non-null    float64
dtypes: float64(2), int64(3)
memory usage: 19.7 KB

In [11]:
df.corr()

,House_Size_sqft,Bedrooms,Age_of_House,Distance_to_City_km,Price_Lakhs
House_Size_sqft,1.000000,0.891500,-0.013785,-0.031477,0.977515
Bedrooms,0.891500,1.000000,0.001341,-0.038867,0.905370
Age_of_House,-0.013785,0.001341,1.000000,0.009671,-0.136553
Distance_to_City_km,-0.031477,-0.038867,0.009671,1.000000,-0.163530
Price_Lakhs,0.977515,0.905370,-0.136553,-0.163530,1.000000

In [22]:
x=df[
    [
        "House_Size_sqft",
        "Bedrooms",
        "Age_of_House",
        "Distance_to_City_km" ]
]
Y=df["Price_Lakhs"]

In [23]:
x_train,x_test,y_train,y_test=train_test_split(
    x,
   Y,
    test_size=0.2,
    random_state=42
    )

In [26]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(400, 4)
(100, 4)
(400,)
(100,)

In [27]:
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [15]:
knn=KNeighborsRegressor(n_neighbors=5)

In [29]:
knn.fit(x_train_scaled,y_train)

KNeighborsRegressor()

In [30]:
y_pred=knn.predict(x_test)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but KNeighborsRegressor was fitted without feature names
  warnings.warn(

In [32]:
mae=mean_absolute_error(y_test, y_pred)
print("mean absolute error",mae)
mse=mean_squared_error(y_test, y_pred)
print("mean squared error",mse)
rmse=np.sqrt(mse)
print("root mean squared error",rmse)
r2 = r2_score(y_test, y_pred)
print("r2 score",r2)

mean absolute error 99.47280000000002
mean squared error 14077.186576000002
root mean squared error 118.64732013829897
r2 score -1.9479013668872054

In [35]:
new_house=[[1700,3,4,5,]]
new_house_scaled=scaler.transform(new_house)
pred=knn.predict(new_house_scaled)
print(pred[0])

103.8

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(