<a href="https://colab.research.google.com/github/bharathrockstar813-byte/e-commerce-/blob/main/stock%209.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#time series data
#tikme series data is data collected over time
#stock price
#30 may reliance 11 1000
12 1100
1 1500
2 5--
3 1000
#in normal data row order is  not importan
#in

In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("/content/drive/MyDrive/data cleaing/stock_price_data (1).csv")

In [4]:
df

          Date  Stock_Price  Volume
0   2025-01-01        100.0  1000.0
1   2025-01-02        102.0  1200.0
2   2025-01-03        105.0  1500.0
3   2025-01-05          NaN  1400.0
4   2025-01-06        108.0     NaN
5   2025-01-08        112.0  1700.0
6   2025-01-09        110.0  1650.0
7   2025-01-10          NaN  1800.0
8   2025-01-12        118.0  2000.0
9   2025-01-13        121.0     NaN
10  2025-01-15        125.0  2200.0

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         11 non-null     datetime64[ns]
 1   Stock_Price  9 non-null      float64
 2   Volume       9 non-null      float64
dtypes: datetime64[ns](1), float64(2)
memory usage: 396.0 bytes

In [13]:
df.head()

        Date  Stock_Price  Volume
0 2025-01-01        100.0  1000.0
1 2025-01-02        102.0  1200.0
2 2025-01-03        105.0  1500.0
3 2025-01-05          NaN  1400.0
4 2025-01-06        108.0     NaN

In [ ]:
#srep1 find datatpyues if datatpyes is nit proper ffromat just change change form

In [15]:
#converting data column
df["Date"]=pd.to_datetime(df["Date"])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         11 non-null     datetime64[ns]
 1   Stock_Price  9 non-null      float64
 2   Volume       9 non-null      float64
dtypes: datetime64[ns](1), float64(2)
memory usage: 396.0 bytes

In [16]:
#sort the values
dfd=df.sort_values("Date")
dfd

         Date  Stock_Price  Volume
0  2025-01-01        100.0  1000.0
1  2025-01-02        102.0  1200.0
2  2025-01-03        105.0  1500.0
3  2025-01-05          NaN  1400.0
4  2025-01-06        108.0     NaN
5  2025-01-08        112.0  1700.0
6  2025-01-09        110.0  1650.0
7  2025-01-10          NaN  1800.0
8  2025-01-12        118.0  2000.0
9  2025-01-13        121.0     NaN
10 2025-01-15        125.0  2200.0

In [18]:
#set date as index
dfd.set_index("Date", inplace=True)
dfd

            Stock_Price  Volume
Date
2025-01-01        100.0  1000.0
2025-01-02        102.0  1200.0
2025-01-03        105.0  1500.0
2025-01-05          NaN  1400.0
2025-01-06        108.0     NaN
2025-01-08        112.0  1700.0
2025-01-09        110.0  1650.0
2025-01-10          NaN  1800.0
2025-01-12        118.0  2000.0
2025-01-13        121.0     NaN
2025-01-15        125.0  2200.0

In [20]:
#so we can create missing date too
dfd=dfd.asfreq("D")
dfd

            Stock_Price  Volume
Date
2025-01-01        100.0  1000.0
2025-01-02        102.0  1200.0
2025-01-03        105.0  1500.0
2025-01-04          NaN     NaN
2025-01-05          NaN  1400.0
2025-01-06        108.0     NaN
2025-01-07          NaN     NaN
2025-01-08        112.0  1700.0
2025-01-09        110.0  1650.0
2025-01-10          NaN  1800.0
2025-01-11          NaN     NaN
2025-01-12        118.0  2000.0
2025-01-13        121.0     NaN
2025-01-14          NaN     NaN
2025-01-15        125.0  2200.0

In [21]:
#d daily
h
m
y
h
#handling missing value
day 100
day2
day3
day4
#intrplation means fillimng missing value by using
#the values before and after them and wstimating
#what the mkissing value shoulde be

In [24]:
dfd["Stock_Price"]=dfd["Stock_Price"].interpolate()
dfd["Volume"]=dfd["Volume"].interpolate()
dfd

            Stock_Price       Volume
Date
2025-01-01   100.000000  1000.000000
2025-01-02   102.000000  1200.000000
2025-01-03   105.000000  1500.000000
2025-01-04   106.000000  1450.000000
2025-01-05   107.000000  1400.000000
2025-01-06   108.000000  1500.000000
2025-01-07   110.000000  1600.000000
2025-01-08   112.000000  1700.000000
2025-01-09   110.000000  1650.000000
2025-01-10   112.666667  1800.000000
2025-01-11   115.333333  1900.000000
2025-01-12   118.000000  2000.000000
2025-01-13   121.000000  2066.666667
2025-01-14   123.000000  2133.333333
2025-01-15   125.000000  2200.000000

In [ ]:
#forwared replace a missing value with the previous vale
#backwardpill repalce a missing value with next availlble valuefill

In [27]:
#convert data features
dfd["Year"]=dfd.index.year
dfd["Monnth"]=dfd.index.month
dfd["Day"]=dfd.index.day
dfd
dfd["dayofweek"]=dfd.index.dayofweek
dfd

            Stock_Price       Volume  Year  Monnth  Day  dayofweek
Date
2025-01-01   100.000000  1000.000000  2025       1    1          2
2025-01-02   102.000000  1200.000000  2025       1    2          3
2025-01-03   105.000000  1500.000000  2025       1    3          4
2025-01-04   106.000000  1450.000000  2025       1    4          5
2025-01-05   107.000000  1400.000000  2025       1    5          6
2025-01-06   108.000000  1500.000000  2025       1    6          0
2025-01-07   110.000000  1600.000000  2025       1    7          1
2025-01-08   112.000000  1700.000000  2025       1    8          2
2025-01-09   110.000000  1650.000000  2025       1    9          3
2025-01-10   112.666667  1800.000000  2025       1   10          4
2025-01-11   115.333333  1900.000000  2025       1   11          5
2025-01-12   118.000000  2000.000000  2025       1   12          6
2025-01-13   121.000000  2066.666667  2025       1   13          0
2025-01-14   123.000000  2133.333333  2025       1   14          1
2025-01-15   125.000000  2200.000000  2025       1   15          2

In [28]:
dfd["weekend"]=(dfd.index.dayofweek>=5).astype(int)
dfd

            Stock_Price       Volume  Year  Monnth  Day  dayofweek  weekend
Date
2025-01-01   100.000000  1000.000000  2025       1    1          2        0
2025-01-02   102.000000  1200.000000  2025       1    2          3        0
2025-01-03   105.000000  1500.000000  2025       1    3          4        0
2025-01-04   106.000000  1450.000000  2025       1    4          5        1
2025-01-05   107.000000  1400.000000  2025       1    5          6        1
2025-01-06   108.000000  1500.000000  2025       1    6          0        0
2025-01-07   110.000000  1600.000000  2025       1    7          1        0
2025-01-08   112.000000  1700.000000  2025       1    8          2        0
2025-01-09   110.000000  1650.000000  2025       1    9          3        0
2025-01-10   112.666667  1800.000000  2025       1   10          4        0
2025-01-11   115.333333  1900.000000  2025       1   11          5        1
2025-01-12   118.000000  2000.000000  2025       1   12          6        1
2025-01-13   121.000000  2066.666667  2025       1   13          0        0
2025-01-14   123.000000  2133.333333  2025       1   14          1        0
2025-01-15   125.000000  2200.000000  2025       1   15          2        0

In [33]:
#lag feature
#a lag feature means use part valuws to predict future value
dfd["lag1"]=dfd["Stock_Price"].shift(1)
dfd
dfd["lag2"]=dfd["Stock_Price"].shift(2)
dfd["moving_average"]=dfd["Stock_Price"].rolling(3).mean()
dfd

,Stock_Price,Volume,Year,Monnth,Day,dayofweek,weekend,lag1,lag2,moving_average
Date,,,,,,,,,,
2025-01-01,100.000000,1000.000000,2025,1,1,2,0,NaN,NaN,NaN
2025-01-02,102.000000,1200.000000,2025,1,2,3,0,100.000000,NaN,NaN
2025-01-03,105.000000,1500.000000,2025,1,3,4,0,102.000000,100.000000,102.333333
2025-01-04,106.000000,1450.000000,2025,1,4,5,1,105.000000,102.000000,104.333333
2025-01-05,107.000000,1400.000000,2025,1,5,6,1,106.000000,105.000000,106.000000
2025-01-06,108.000000,1500.000000,2025,1,6,0,0,107.000000,106.000000,107.000000
2025-01-07,110.000000,1600.000000,2025,1,7,1,0,108.000000,107.000000,108.333333
2025-01-08,112.000000,1700.000000,2025,1,8,2,0,110.000000,108.000000,110.000000
2025-01-09,110.000000,1650.000000,2025,1,9,3,0,112.000000,110.000000,110.666667
2025-01-10,112.666667,1800.000000,2025,1,10,4,0,110.000000,112.000000,111.555556
2025-01-11,115.333333,1900.000000,2025,1,11,5,1,112.666667,110.000000,112.666667
2025-01-12,118.000000,2000.000000,2025,1,12,6,1,115.333333,112.666667,115.333333
2025-01-13,121.000000,2066.666667,2025,1,13,0,0,118.000000,115.333333,118.111111
2025-01-14,123.000000,2133.333333,2025,1,14,1,0,121.000000,118.000000,120.666667
2025-01-15,125.000000,2200.000000,2025,1,15,2,0,123.000000,121.000000,123.000000

In [ ]:
age salary salary (hihpay ingyesorono)
20   100000  no
30   200000  yes

In [ ]:
scaling is nothing but brining all feature to a similar scale
mijn max scalingstandaization

In [4]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [5]:
df=pd.read_csv("/content/drive/MyDrive/data cleaing/scalingminmax_student_data (1).csv")

In [6]:
df

   Study_Hours  Income
0            2   50000
1            4   80000
2            6  100000
3            8  120000
4           10  150000

In [10]:
scaler=minmax_scale()
df["Income"]=scaler.fit_transform(df[["Income"]])
print(df)

NameError: name 'minmax_scale' is not defined