<a href="https://colab.research.google.com/github/bharathrockstar813-byte/e-commerce-/blob/main/strinbg_processing_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [4]:
df=pd.read_csv("/content/drive/MyDrive/data cleaing/string_processing_dataset (1).csv")

In [5]:
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date
0,Santhosh Chevuri,santhosh@gmail.com,Vijayawada,Rs 1000,9876543210,PRD-101,12-Jan-2024
1,RAJU KUMAR,RAJU@YAHOO.COM,HYDERABAD,$250,9123456789,PRD-202,05-Feb-2024
2,kiran reddy,kiran@gmail.com,vizag,"Rs 3,500",9988776655,PRD-303,18-Mar-2024
3,SURESH BABU,suresh@outlook.com,Guntur,"$1,200",9871234567,PRD-404,22-Apr-2024
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,Rs 750,9012345678,PRD-505,30-May-2024

In [8]:
df["email"]=df["email"].str.lower() # we are covintering intpo lower case
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date
0,Santhosh Chevuri,santhosh@gmail.com,Vijayawada,Rs 1000,9876543210,PRD-101,12-Jan-2024
1,RAJU KUMAR,raju@yahoo.com,HYDERABAD,$250,9123456789,PRD-202,05-Feb-2024
2,kiran reddy,kiran@gmail.com,vizag,"Rs 3,500",9988776655,PRD-303,18-Mar-2024
3,SURESH BABU,suresh@outlook.com,Guntur,"$1,200",9871234567,PRD-404,22-Apr-2024
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,Rs 750,9012345678,PRD-505,30-May-2024

,customer_name,email,city,purchase_amount,phone,product_code,join_date
0,Santhosh Chevuri,santhosh@gmail.com,Vijayawada,Rs 1000,9876543210,PRD-101,12-Jan-2024
1,RAJU KUMAR,raju@yahoo.com,HYDERABAD,$250,9123456789,PRD-202,05-Feb-2024
2,kiran reddy,kiran@gmail.com,vizag,"Rs 3,500",9988776655,PRD-303,18-Mar-2024
3,SURESH BABU,suresh@outlook.com,Guntur,"$1,200",9871234567,PRD-404,22-Apr-2024
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,Rs 750,9012345678,PRD-505,30-May-2024

In [10]:
df["city"]=df["city"].str.upper() # we are covintering intpo upper case
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date
0,Santhosh Chevuri,SANTHOSH@GMAIL.COM,VIJAYAWADA,Rs 1000,9876543210,PRD-101,12-Jan-2024
1,RAJU KUMAR,RAJU@YAHOO.COM,HYDERABAD,$250,9123456789,PRD-202,05-Feb-2024
2,kiran reddy,KIRAN@GMAIL.COM,VIZAG,"Rs 3,500",9988776655,PRD-303,18-Mar-2024
3,SURESH BABU,SURESH@OUTLOOK.COM,GUNTUR,"$1,200",9871234567,PRD-404,22-Apr-2024
4,Lakshmi Devi,LAKSHMI@GMAIL.COM,TIRUPATI,Rs 750,9012345678,PRD-505,30-May-2024

In [11]:
df["customer_name"]=df["customer_name"].str.title() # we are covintering intpo lower case
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date
0,Santhosh Chevuri,SANTHOSH@GMAIL.COM,VIJAYAWADA,Rs 1000,9876543210,PRD-101,12-Jan-2024
1,Raju Kumar,RAJU@YAHOO.COM,HYDERABAD,$250,9123456789,PRD-202,05-Feb-2024
2,Kiran Reddy,KIRAN@GMAIL.COM,VIZAG,"Rs 3,500",9988776655,PRD-303,18-Mar-2024
3,Suresh Babu,SURESH@OUTLOOK.COM,GUNTUR,"$1,200",9871234567,PRD-404,22-Apr-2024
4,Lakshmi Devi,LAKSHMI@GMAIL.COM,TIRUPATI,Rs 750,9012345678,PRD-505,30-May-2024

In [12]:
df["name_lenth"]=df["customer_name"].str.len() # we are covintering intpo lower case
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,name_lenth
0,Santhosh Chevuri,SANTHOSH@GMAIL.COM,VIJAYAWADA,Rs 1000,9876543210,PRD-101,12-Jan-2024,19
1,Raju Kumar,RAJU@YAHOO.COM,HYDERABAD,$250,9123456789,PRD-202,05-Feb-2024,10
2,Kiran Reddy,KIRAN@GMAIL.COM,VIZAG,"Rs 3,500",9988776655,PRD-303,18-Mar-2024,13
3,Suresh Babu,SURESH@OUTLOOK.COM,GUNTUR,"$1,200",9871234567,PRD-404,22-Apr-2024,13
4,Lakshmi Devi,LAKSHMI@GMAIL.COM,TIRUPATI,Rs 750,9012345678,PRD-505,30-May-2024,12

In [ ]:
#regex=flazse tella a pandas to treat the value as noraml text and not as aspecial pattrn

In [14]:
df["purchase_amount"]=df["purchase_amount"].str.replace("$","",regex=False)
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,name_lenth
0,Santhosh Chevuri,SANTHOSH@GMAIL.COM,VIJAYAWADA,1000,9876543210,PRD-101,12-Jan-2024,19
1,Raju Kumar,RAJU@YAHOO.COM,HYDERABAD,250,9123456789,PRD-202,05-Feb-2024,10
2,Kiran Reddy,KIRAN@GMAIL.COM,VIZAG,"3,500",9988776655,PRD-303,18-Mar-2024,13
3,Suresh Babu,SURESH@OUTLOOK.COM,GUNTUR,"1,200",9871234567,PRD-404,22-Apr-2024,13
4,Lakshmi Devi,LAKSHMI@GMAIL.COM,TIRUPATI,750,9012345678,PRD-505,30-May-2024,12

In [15]:
df["purchase_amount"]=df["purchase_amount"].str.replace("Rs","",regex=False)
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,name_lenth
0,Santhosh Chevuri,SANTHOSH@GMAIL.COM,VIJAYAWADA,1000,9876543210,PRD-101,12-Jan-2024,19
1,Raju Kumar,RAJU@YAHOO.COM,HYDERABAD,250,9123456789,PRD-202,05-Feb-2024,10
2,Kiran Reddy,KIRAN@GMAIL.COM,VIZAG,"3,500",9988776655,PRD-303,18-Mar-2024,13
3,Suresh Babu,SURESH@OUTLOOK.COM,GUNTUR,"1,200",9871234567,PRD-404,22-Apr-2024,13
4,Lakshmi Devi,LAKSHMI@GMAIL.COM,TIRUPATI,750,9012345678,PRD-505,30-May-2024,12

In [16]:
df["purchase_amount"]=df["purchase_amount"].str.replace(",","",regex=False)
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,name_lenth
0,Santhosh Chevuri,SANTHOSH@GMAIL.COM,VIJAYAWADA,1000,9876543210,PRD-101,12-Jan-2024,19
1,Raju Kumar,RAJU@YAHOO.COM,HYDERABAD,250,9123456789,PRD-202,05-Feb-2024,10
2,Kiran Reddy,KIRAN@GMAIL.COM,VIZAG,3500,9988776655,PRD-303,18-Mar-2024,13
3,Suresh Babu,SURESH@OUTLOOK.COM,GUNTUR,1200,9871234567,PRD-404,22-Apr-2024,13
4,Lakshmi Devi,LAKSHMI@GMAIL.COM,TIRUPATI,750,9012345678,PRD-505,30-May-2024,12

In [18]:
df["is_mail"]=df["email"].str.contains("gmail")
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,name_lenth,is_mail
0,Santhosh Chevuri,SANTHOSH@GMAIL.COM,VIJAYAWADA,1000,9876543210,PRD-101,12-Jan-2024,19,False
1,Raju Kumar,RAJU@YAHOO.COM,HYDERABAD,250,9123456789,PRD-202,05-Feb-2024,10,False
2,Kiran Reddy,KIRAN@GMAIL.COM,VIZAG,3500,9988776655,PRD-303,18-Mar-2024,13,False
3,Suresh Babu,SURESH@OUTLOOK.COM,GUNTUR,1200,9871234567,PRD-404,22-Apr-2024,13,False
4,Lakshmi Devi,LAKSHMI@GMAIL.COM,TIRUPATI,750,9012345678,PRD-505,30-May-2024,12,False

In [20]:
df["startswithv"]=df["city"].str.startswith("v")
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,name_lenth,is_mail,startswithv
0,Santhosh Chevuri,SANTHOSH@GMAIL.COM,VIJAYAWADA,1000,9876543210,PRD-101,12-Jan-2024,19,False,False
1,Raju Kumar,RAJU@YAHOO.COM,HYDERABAD,250,9123456789,PRD-202,05-Feb-2024,10,False,False
2,Kiran Reddy,KIRAN@GMAIL.COM,VIZAG,3500,9988776655,PRD-303,18-Mar-2024,13,False,False
3,Suresh Babu,SURESH@OUTLOOK.COM,GUNTUR,1200,9871234567,PRD-404,22-Apr-2024,13,False,False
4,Lakshmi Devi,LAKSHMI@GMAIL.COM,TIRUPATI,750,9012345678,PRD-505,30-May-2024,12,False,False

In [21]:
df["email_parts"]=df["email"].str.split("@")
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,name_lenth,is_mail,startswithv,email_parts
0,Santhosh Chevuri,SANTHOSH@GMAIL.COM,VIJAYAWADA,1000,9876543210,PRD-101,12-Jan-2024,19,False,False,"[SANTHOSH, GMAIL.COM]"
1,Raju Kumar,RAJU@YAHOO.COM,HYDERABAD,250,9123456789,PRD-202,05-Feb-2024,10,False,False,"[RAJU, YAHOO.COM]"
2,Kiran Reddy,KIRAN@GMAIL.COM,VIZAG,3500,9988776655,PRD-303,18-Mar-2024,13,False,False,"[KIRAN, GMAIL.COM]"
3,Suresh Babu,SURESH@OUTLOOK.COM,GUNTUR,1200,9871234567,PRD-404,22-Apr-2024,13,False,False,"[SURESH, OUTLOOK.COM]"
4,Lakshmi Devi,LAKSHMI@GMAIL.COM,TIRUPATI,750,9012345678,PRD-505,30-May-2024,12,False,False,"[LAKSHMI, GMAIL.COM]"

In [22]:
df["username"]=df["email"].str.split("@").str[0]
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,name_lenth,is_mail,startswithv,email_parts,username
0,Santhosh Chevuri,SANTHOSH@GMAIL.COM,VIJAYAWADA,1000,9876543210,PRD-101,12-Jan-2024,19,False,False,"[SANTHOSH, GMAIL.COM]",SANTHOSH
1,Raju Kumar,RAJU@YAHOO.COM,HYDERABAD,250,9123456789,PRD-202,05-Feb-2024,10,False,False,"[RAJU, YAHOO.COM]",RAJU
2,Kiran Reddy,KIRAN@GMAIL.COM,VIZAG,3500,9988776655,PRD-303,18-Mar-2024,13,False,False,"[KIRAN, GMAIL.COM]",KIRAN
3,Suresh Babu,SURESH@OUTLOOK.COM,GUNTUR,1200,9871234567,PRD-404,22-Apr-2024,13,False,False,"[SURESH, OUTLOOK.COM]",SURESH
4,Lakshmi Devi,LAKSHMI@GMAIL.COM,TIRUPATI,750,9012345678,PRD-505,30-May-2024,12,False,False,"[LAKSHMI, GMAIL.COM]",LAKSHMI

In [23]:
df["city_code"]=df["city"].str[:3]
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,name_lenth,is_mail,startswithv,email_parts,username,city_code
0,Santhosh Chevuri,SANTHOSH@GMAIL.COM,VIJAYAWADA,1000,9876543210,PRD-101,12-Jan-2024,19,False,False,"[SANTHOSH, GMAIL.COM]",SANTHOSH,VIJ
1,Raju Kumar,RAJU@YAHOO.COM,HYDERABAD,250,9123456789,PRD-202,05-Feb-2024,10,False,False,"[RAJU, YAHOO.COM]",RAJU,HYD
2,Kiran Reddy,KIRAN@GMAIL.COM,VIZAG,3500,9988776655,PRD-303,18-Mar-2024,13,False,False,"[KIRAN, GMAIL.COM]",KIRAN,VI
3,Suresh Babu,SURESH@OUTLOOK.COM,GUNTUR,1200,9871234567,PRD-404,22-Apr-2024,13,False,False,"[SURESH, OUTLOOK.COM]",SURESH,GUN
4,Lakshmi Devi,LAKSHMI@GMAIL.COM,TIRUPATI,750,9012345678,PRD-505,30-May-2024,12,False,False,"[LAKSHMI, GMAIL.COM]",LAKSHMI,TIR

In [24]:
df["is_numeric"]=df["phone"].astype(str).str.isnumeric()
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,name_lenth,is_mail,startswithv,email_parts,username,city_code,is_numeric
0,Santhosh Chevuri,SANTHOSH@GMAIL.COM,VIJAYAWADA,1000,9876543210,PRD-101,12-Jan-2024,19,False,False,"[SANTHOSH, GMAIL.COM]",SANTHOSH,VIJ,True
1,Raju Kumar,RAJU@YAHOO.COM,HYDERABAD,250,9123456789,PRD-202,05-Feb-2024,10,False,False,"[RAJU, YAHOO.COM]",RAJU,HYD,True
2,Kiran Reddy,KIRAN@GMAIL.COM,VIZAG,3500,9988776655,PRD-303,18-Mar-2024,13,False,False,"[KIRAN, GMAIL.COM]",KIRAN,VI,True
3,Suresh Babu,SURESH@OUTLOOK.COM,GUNTUR,1200,9871234567,PRD-404,22-Apr-2024,13,False,False,"[SURESH, OUTLOOK.COM]",SURESH,GUN,True
4,Lakshmi Devi,LAKSHMI@GMAIL.COM,TIRUPATI,750,9012345678,PRD-505,30-May-2024,12,False,False,"[LAKSHMI, GMAIL.COM]",LAKSHMI,TIR,True

In [25]:
df["product_code"]=df["product_code"].str.removeprefix("PRD-")
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,name_lenth,is_mail,startswithv,email_parts,username,city_code,is_numeric
0,Santhosh Chevuri,SANTHOSH@GMAIL.COM,VIJAYAWADA,1000,9876543210,101,12-Jan-2024,19,False,False,"[SANTHOSH, GMAIL.COM]",SANTHOSH,VIJ,True
1,Raju Kumar,RAJU@YAHOO.COM,HYDERABAD,250,9123456789,202,05-Feb-2024,10,False,False,"[RAJU, YAHOO.COM]",RAJU,HYD,True
2,Kiran Reddy,KIRAN@GMAIL.COM,VIZAG,3500,9988776655,303,18-Mar-2024,13,False,False,"[KIRAN, GMAIL.COM]",KIRAN,VI,True
3,Suresh Babu,SURESH@OUTLOOK.COM,GUNTUR,1200,9871234567,404,22-Apr-2024,13,False,False,"[SURESH, OUTLOOK.COM]",SURESH,GUN,True
4,Lakshmi Devi,LAKSHMI@GMAIL.COM,TIRUPATI,750,9012345678,505,30-May-2024,12,False,False,"[LAKSHMI, GMAIL.COM]",LAKSHMI,TIR,True

In [28]:
df["product_code"]=df["product_code"].str.removesuffix("PRD--")
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,name_lenth,is_mail,startswithv,email_parts,username,city_code,is_numeric
0,Santhosh Chevuri,SANTHOSH@GMAIL.COM,VIJAYAWADA,1000,9876543210,101,12-Jan-2024,19,False,False,"[SANTHOSH, GMAIL.COM]",SANTHOSH,VIJ,True
1,Raju Kumar,RAJU@YAHOO.COM,HYDERABAD,250,9123456789,202,05-Feb-2024,10,False,False,"[RAJU, YAHOO.COM]",RAJU,HYD,True
2,Kiran Reddy,KIRAN@GMAIL.COM,VIZAG,3500,9988776655,303,18-Mar-2024,13,False,False,"[KIRAN, GMAIL.COM]",KIRAN,VI,True
3,Suresh Babu,SURESH@OUTLOOK.COM,GUNTUR,1200,9871234567,404,22-Apr-2024,13,False,False,"[SURESH, OUTLOOK.COM]",SURESH,GUN,True
4,Lakshmi Devi,LAKSHMI@GMAIL.COM,TIRUPATI,750,9012345678,505,30-May-2024,12,False,False,"[LAKSHMI, GMAIL.COM]",LAKSHMI,TIR,True

In [ ]:
#task 5

In [32]:
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,name_lenth,is_mail,startswithv,email_parts,username,city_code,is_numeric
0,Santhosh Chevuri,SANTHOSH@GMAIL.COM,VIJAYAWADA,1000,9876543210,101,12-Jan-2024,19,False,False,"[SANTHOSH, GMAIL.COM]",SANTHOSH,VIJ,True
1,Raju Kumar,RAJU@YAHOO.COM,HYDERABAD,250,9123456789,202,05-Feb-2024,10,False,False,"[RAJU, YAHOO.COM]",RAJU,HYD,True
2,Kiran Reddy,KIRAN@GMAIL.COM,VIZAG,3500,9988776655,303,18-Mar-2024,13,False,False,"[KIRAN, GMAIL.COM]",KIRAN,VI,True
3,Suresh Babu,SURESH@OUTLOOK.COM,GUNTUR,1200,9871234567,404,22-Apr-2024,13,False,False,"[SURESH, OUTLOOK.COM]",SURESH,GUN,True
4,Lakshmi Devi,LAKSHMI@GMAIL.COM,TIRUPATI,750,9012345678,505,30-May-2024,12,False,False,"[LAKSHMI, GMAIL.COM]",LAKSHMI,TIR,True

In [33]:
df["name"]=df["customer_name"].str.title()
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,name_lenth,is_mail,startswithv,email_parts,username,city_code,is_numeric,name
0,Santhosh Chevuri,SANTHOSH@GMAIL.COM,VIJAYAWADA,1000,9876543210,101,12-Jan-2024,19,False,False,"[SANTHOSH, GMAIL.COM]",SANTHOSH,VIJ,True,Santhosh Chevuri
1,Raju Kumar,RAJU@YAHOO.COM,HYDERABAD,250,9123456789,202,05-Feb-2024,10,False,False,"[RAJU, YAHOO.COM]",RAJU,HYD,True,Raju Kumar
2,Kiran Reddy,KIRAN@GMAIL.COM,VIZAG,3500,9988776655,303,18-Mar-2024,13,False,False,"[KIRAN, GMAIL.COM]",KIRAN,VI,True,Kiran Reddy
3,Suresh Babu,SURESH@OUTLOOK.COM,GUNTUR,1200,9871234567,404,22-Apr-2024,13,False,False,"[SURESH, OUTLOOK.COM]",SURESH,GUN,True,Suresh Babu
4,Lakshmi Devi,LAKSHMI@GMAIL.COM,TIRUPATI,750,9012345678,505,30-May-2024,12,False,False,"[LAKSHMI, GMAIL.COM]",LAKSHMI,TIR,True,Lakshmi Devi

In [34]:
df["email"]=df["email"].str.lower()
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,name_lenth,is_mail,startswithv,email_parts,username,city_code,is_numeric,name
0,Santhosh Chevuri,santhosh@gmail.com,VIJAYAWADA,1000,9876543210,101,12-Jan-2024,19,False,False,"[SANTHOSH, GMAIL.COM]",SANTHOSH,VIJ,True,Santhosh Chevuri
1,Raju Kumar,raju@yahoo.com,HYDERABAD,250,9123456789,202,05-Feb-2024,10,False,False,"[RAJU, YAHOO.COM]",RAJU,HYD,True,Raju Kumar
2,Kiran Reddy,kiran@gmail.com,VIZAG,3500,9988776655,303,18-Mar-2024,13,False,False,"[KIRAN, GMAIL.COM]",KIRAN,VI,True,Kiran Reddy
3,Suresh Babu,suresh@outlook.com,GUNTUR,1200,9871234567,404,22-Apr-2024,13,False,False,"[SURESH, OUTLOOK.COM]",SURESH,GUN,True,Suresh Babu
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,750,9012345678,505,30-May-2024,12,False,False,"[LAKSHMI, GMAIL.COM]",LAKSHMI,TIR,True,Lakshmi Devi

In [36]:
df["name"]=df["customer_name"].str.upper()
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,name_lenth,is_mail,startswithv,email_parts,username,city_code,is_numeric,name
0,Santhosh Chevuri,santhosh@gmail.com,VIJAYAWADA,1000,9876543210,101,12-Jan-2024,19,False,False,"[SANTHOSH, GMAIL.COM]",SANTHOSH,VIJ,True,SANTHOSH CHEVURI
1,Raju Kumar,raju@yahoo.com,HYDERABAD,250,9123456789,202,05-Feb-2024,10,False,False,"[RAJU, YAHOO.COM]",RAJU,HYD,True,RAJU KUMAR
2,Kiran Reddy,kiran@gmail.com,VIZAG,3500,9988776655,303,18-Mar-2024,13,False,False,"[KIRAN, GMAIL.COM]",KIRAN,VI,True,KIRAN REDDY
3,Suresh Babu,suresh@outlook.com,GUNTUR,1200,9871234567,404,22-Apr-2024,13,False,False,"[SURESH, OUTLOOK.COM]",SURESH,GUN,True,SURESH BABU
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,750,9012345678,505,30-May-2024,12,False,False,"[LAKSHMI, GMAIL.COM]",LAKSHMI,TIR,True,LAKSHMI DEVI

In [37]:
df["account"]=df["purchase_amount"].str.upper()
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,name_lenth,is_mail,startswithv,email_parts,username,city_code,is_numeric,name,account
0,Santhosh Chevuri,santhosh@gmail.com,VIJAYAWADA,1000,9876543210,101,12-Jan-2024,19,False,False,"[SANTHOSH, GMAIL.COM]",SANTHOSH,VIJ,True,SANTHOSH CHEVURI,1000
1,Raju Kumar,raju@yahoo.com,HYDERABAD,250,9123456789,202,05-Feb-2024,10,False,False,"[RAJU, YAHOO.COM]",RAJU,HYD,True,RAJU KUMAR,250
2,Kiran Reddy,kiran@gmail.com,VIZAG,3500,9988776655,303,18-Mar-2024,13,False,False,"[KIRAN, GMAIL.COM]",KIRAN,VI,True,KIRAN REDDY,3500
3,Suresh Babu,suresh@outlook.com,GUNTUR,1200,9871234567,404,22-Apr-2024,13,False,False,"[SURESH, OUTLOOK.COM]",SURESH,GUN,True,SURESH BABU,1200
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,750,9012345678,505,30-May-2024,12,False,False,"[LAKSHMI, GMAIL.COM]",LAKSHMI,TIR,True,LAKSHMI DEVI,750

In [38]:
df["removing"]=df["purchase_amount"].str.replace("Rs","",regex=False)
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,name_lenth,is_mail,startswithv,email_parts,username,city_code,is_numeric,name,account,removing
0,Santhosh Chevuri,santhosh@gmail.com,VIJAYAWADA,1000,9876543210,101,12-Jan-2024,19,False,False,"[SANTHOSH, GMAIL.COM]",SANTHOSH,VIJ,True,SANTHOSH CHEVURI,1000,1000
1,Raju Kumar,raju@yahoo.com,HYDERABAD,250,9123456789,202,05-Feb-2024,10,False,False,"[RAJU, YAHOO.COM]",RAJU,HYD,True,RAJU KUMAR,250,250
2,Kiran Reddy,kiran@gmail.com,VIZAG,3500,9988776655,303,18-Mar-2024,13,False,False,"[KIRAN, GMAIL.COM]",KIRAN,VI,True,KIRAN REDDY,3500,3500
3,Suresh Babu,suresh@outlook.com,GUNTUR,1200,9871234567,404,22-Apr-2024,13,False,False,"[SURESH, OUTLOOK.COM]",SURESH,GUN,True,SURESH BABU,1200,1200
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,750,9012345678,505,30-May-2024,12,False,False,"[LAKSHMI, GMAIL.COM]",LAKSHMI,TIR,True,LAKSHMI DEVI,750,750

In [39]:
df["is_numeric"]=df["phone"].astype(str).str.isnumeric()
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,name_lenth,is_mail,startswithv,email_parts,username,city_code,is_numeric,name,account,removing
0,Santhosh Chevuri,santhosh@gmail.com,VIJAYAWADA,1000,9876543210,101,12-Jan-2024,19,False,False,"[SANTHOSH, GMAIL.COM]",SANTHOSH,VIJ,True,SANTHOSH CHEVURI,1000,1000
1,Raju Kumar,raju@yahoo.com,HYDERABAD,250,9123456789,202,05-Feb-2024,10,False,False,"[RAJU, YAHOO.COM]",RAJU,HYD,True,RAJU KUMAR,250,250
2,Kiran Reddy,kiran@gmail.com,VIZAG,3500,9988776655,303,18-Mar-2024,13,False,False,"[KIRAN, GMAIL.COM]",KIRAN,VI,True,KIRAN REDDY,3500,3500
3,Suresh Babu,suresh@outlook.com,GUNTUR,1200,9871234567,404,22-Apr-2024,13,False,False,"[SURESH, OUTLOOK.COM]",SURESH,GUN,True,SURESH BABU,1200,1200
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,750,9012345678,505,30-May-2024,12,False,False,"[LAKSHMI, GMAIL.COM]",LAKSHMI,TIR,True,LAKSHMI DEVI,750,750

In [40]:
df["username"]=df["email"].str.contains("gmail")
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,name_lenth,is_mail,startswithv,email_parts,username,city_code,is_numeric,name,account,removing
0,Santhosh Chevuri,santhosh@gmail.com,VIJAYAWADA,1000,9876543210,101,12-Jan-2024,19,False,False,"[SANTHOSH, GMAIL.COM]",True,VIJ,True,SANTHOSH CHEVURI,1000,1000
1,Raju Kumar,raju@yahoo.com,HYDERABAD,250,9123456789,202,05-Feb-2024,10,False,False,"[RAJU, YAHOO.COM]",False,HYD,True,RAJU KUMAR,250,250
2,Kiran Reddy,kiran@gmail.com,VIZAG,3500,9988776655,303,18-Mar-2024,13,False,False,"[KIRAN, GMAIL.COM]",True,VI,True,KIRAN REDDY,3500,3500
3,Suresh Babu,suresh@outlook.com,GUNTUR,1200,9871234567,404,22-Apr-2024,13,False,False,"[SURESH, OUTLOOK.COM]",False,GUN,True,SURESH BABU,1200,1200
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,750,9012345678,505,30-May-2024,12,False,False,"[LAKSHMI, GMAIL.COM]",True,TIR,True,LAKSHMI DEVI,750,750

In [41]:
df["city_code"]=df["city"].str[:3]
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,name_lenth,is_mail,startswithv,email_parts,username,city_code,is_numeric,name,account,removing
0,Santhosh Chevuri,santhosh@gmail.com,VIJAYAWADA,1000,9876543210,101,12-Jan-2024,19,False,False,"[SANTHOSH, GMAIL.COM]",True,VIJ,True,SANTHOSH CHEVURI,1000,1000
1,Raju Kumar,raju@yahoo.com,HYDERABAD,250,9123456789,202,05-Feb-2024,10,False,False,"[RAJU, YAHOO.COM]",False,HYD,True,RAJU KUMAR,250,250
2,Kiran Reddy,kiran@gmail.com,VIZAG,3500,9988776655,303,18-Mar-2024,13,False,False,"[KIRAN, GMAIL.COM]",True,VI,True,KIRAN REDDY,3500,3500
3,Suresh Babu,suresh@outlook.com,GUNTUR,1200,9871234567,404,22-Apr-2024,13,False,False,"[SURESH, OUTLOOK.COM]",False,GUN,True,SURESH BABU,1200,1200
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,750,9012345678,505,30-May-2024,12,False,False,"[LAKSHMI, GMAIL.COM]",True,TIR,True,LAKSHMI DEVI,750,750

In [42]:
df["product_code"]=df["product_code"].str.removeprefix("PRD-")
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,name_lenth,is_mail,startswithv,email_parts,username,city_code,is_numeric,name,account,removing
0,Santhosh Chevuri,santhosh@gmail.com,VIJAYAWADA,1000,9876543210,101,12-Jan-2024,19,False,False,"[SANTHOSH, GMAIL.COM]",True,VIJ,True,SANTHOSH CHEVURI,1000,1000
1,Raju Kumar,raju@yahoo.com,HYDERABAD,250,9123456789,202,05-Feb-2024,10,False,False,"[RAJU, YAHOO.COM]",False,HYD,True,RAJU KUMAR,250,250
2,Kiran Reddy,kiran@gmail.com,VIZAG,3500,9988776655,303,18-Mar-2024,13,False,False,"[KIRAN, GMAIL.COM]",True,VI,True,KIRAN REDDY,3500,3500
3,Suresh Babu,suresh@outlook.com,GUNTUR,1200,9871234567,404,22-Apr-2024,13,False,False,"[SURESH, OUTLOOK.COM]",False,GUN,True,SURESH BABU,1200,1200
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,750,9012345678,505,30-May-2024,12,False,False,"[LAKSHMI, GMAIL.COM]",True,TIR,True,LAKSHMI DEVI,750,750