<a href="https://colab.research.google.com/github/bharathrockstar813-byte/e-commerce-/blob/main/task_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [7]:
df = pd.read_csv("/content/drive/MyDrive/data cleaing/bank_customer_data (1).csv")
df

,customer_name,email,bank_name,account_type,account_number,balance,branch_city
0,SANthosh Chevuri,SANTHOSH@GMAIL.COM,hdfc bank,savings,ACC-1001,"Rs 1,25,000",hyderabad
1,RAJU kumar,RAJU@YAHOO.COM,ICICI BANK,CURRENT,ACC-1002,"$2,500",VIJAYAWADA
2,kiran REDDY,KIRAN@GMAIL.COM,axis bank,salary,ACC-1003,"Rs 75,000",vizag
3,SURESH BABU,SURESH@OUTLOOK.COM,SBI,SAVINGS,ACC-1004,"$10,000",GUNTUR
4,Lakshmi devi,LAKSHMI@GMAIL.COM,kotak bank,current,ACC-1005,"Rs 50,500",tirupati

In [8]:
# 1
df['customer_name'] = df['customer_name'].str.title()
df

,customer_name,email,bank_name,account_type,account_number,balance,branch_city
0,Santhosh Chevuri,SANTHOSH@GMAIL.COM,hdfc bank,savings,ACC-1001,"Rs 1,25,000",hyderabad
1,Raju Kumar,RAJU@YAHOO.COM,ICICI BANK,CURRENT,ACC-1002,"$2,500",VIJAYAWADA
2,Kiran Reddy,KIRAN@GMAIL.COM,axis bank,salary,ACC-1003,"Rs 75,000",vizag
3,Suresh Babu,SURESH@OUTLOOK.COM,SBI,SAVINGS,ACC-1004,"$10,000",GUNTUR
4,Lakshmi Devi,LAKSHMI@GMAIL.COM,kotak bank,current,ACC-1005,"Rs 50,500",tirupati

In [5]:
df['email'] = df['email'].str.lower()
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date
0,Santhosh Chevuri,santhosh@gmail.com,Vijayawada,Rs 1000,9876543210,PRD-101,12-Jan-2024
1,Raju Kumar,raju@yahoo.com,HYDERABAD,$250,9123456789,PRD-202,05-Feb-2024
2,Kiran Reddy,kiran@gmail.com,vizag,"Rs 3,500",9988776655,PRD-303,18-Mar-2024
3,Suresh Babu,suresh@outlook.com,Guntur,"$1,200",9871234567,PRD-404,22-Apr-2024
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,Rs 750,9012345678,PRD-505,30-May-2024

In [9]:
df['bank_name'] = df['bank_name'].str.upper()
df

,customer_name,email,bank_name,account_type,account_number,balance,branch_city
0,Santhosh Chevuri,SANTHOSH@GMAIL.COM,HDFC BANK,savings,ACC-1001,"Rs 1,25,000",hyderabad
1,Raju Kumar,RAJU@YAHOO.COM,ICICI BANK,CURRENT,ACC-1002,"$2,500",VIJAYAWADA
2,Kiran Reddy,KIRAN@GMAIL.COM,AXIS BANK,salary,ACC-1003,"Rs 75,000",vizag
3,Suresh Babu,SURESH@OUTLOOK.COM,SBI,SAVINGS,ACC-1004,"$10,000",GUNTUR
4,Lakshmi Devi,LAKSHMI@GMAIL.COM,KOTAK BANK,current,ACC-1005,"Rs 50,500",tirupati

In [10]:
df['balance'] = df['balance'].str.replace('Rs', '', regex=False)
df['balance'] = df['balance'].str.replace('$', '', regex=False)
df['balance'] = df['balance'].str.replace(',', '', regex=False)
df['balance'] = df['balance'].str.strip()
df

,customer_name,email,bank_name,account_type,account_number,balance,branch_city
0,Santhosh Chevuri,SANTHOSH@GMAIL.COM,HDFC BANK,savings,ACC-1001,125000,hyderabad
1,Raju Kumar,RAJU@YAHOO.COM,ICICI BANK,CURRENT,ACC-1002,2500,VIJAYAWADA
2,Kiran Reddy,KIRAN@GMAIL.COM,AXIS BANK,salary,ACC-1003,75000,vizag
3,Suresh Babu,SURESH@OUTLOOK.COM,SBI,SAVINGS,ACC-1004,10000,GUNTUR
4,Lakshmi Devi,LAKSHMI@GMAIL.COM,KOTAK BANK,current,ACC-1005,50500,tirupati

In [11]:
df['balance'] = df['balance'].astype(int)
df

,customer_name,email,bank_name,account_type,account_number,balance,branch_city
0,Santhosh Chevuri,SANTHOSH@GMAIL.COM,HDFC BANK,savings,ACC-1001,125000,hyderabad
1,Raju Kumar,RAJU@YAHOO.COM,ICICI BANK,CURRENT,ACC-1002,2500,VIJAYAWADA
2,Kiran Reddy,KIRAN@GMAIL.COM,AXIS BANK,salary,ACC-1003,75000,vizag
3,Suresh Babu,SURESH@OUTLOOK.COM,SBI,SAVINGS,ACC-1004,10000,GUNTUR
4,Lakshmi Devi,LAKSHMI@GMAIL.COM,KOTAK BANK,current,ACC-1005,50500,tirupati

In [12]:
df['domain'] = df['email'].str.split('@').str[1]
df

,customer_name,email,bank_name,account_type,account_number,balance,branch_city,domain
0,Santhosh Chevuri,SANTHOSH@GMAIL.COM,HDFC BANK,savings,ACC-1001,125000,hyderabad,GMAIL.COM
1,Raju Kumar,RAJU@YAHOO.COM,ICICI BANK,CURRENT,ACC-1002,2500,VIJAYAWADA,YAHOO.COM
2,Kiran Reddy,KIRAN@GMAIL.COM,AXIS BANK,salary,ACC-1003,75000,vizag,GMAIL.COM
3,Suresh Babu,SURESH@OUTLOOK.COM,SBI,SAVINGS,ACC-1004,10000,GUNTUR,OUTLOOK.COM
4,Lakshmi Devi,LAKSHMI@GMAIL.COM,KOTAK BANK,current,ACC-1005,50500,tirupati,GMAIL.COM

In [13]:
df['branch_code'] = df['branch_city'].str[:3].str.upper()
df

,customer_name,email,bank_name,account_type,account_number,balance,branch_city,domain,branch_code
0,Santhosh Chevuri,SANTHOSH@GMAIL.COM,HDFC BANK,savings,ACC-1001,125000,hyderabad,GMAIL.COM,HYD
1,Raju Kumar,RAJU@YAHOO.COM,ICICI BANK,CURRENT,ACC-1002,2500,VIJAYAWADA,YAHOO.COM,VIJ
2,Kiran Reddy,KIRAN@GMAIL.COM,AXIS BANK,salary,ACC-1003,75000,vizag,GMAIL.COM,VI
3,Suresh Babu,SURESH@OUTLOOK.COM,SBI,SAVINGS,ACC-1004,10000,GUNTUR,OUTLOOK.COM,GUN
4,Lakshmi Devi,LAKSHMI@GMAIL.COM,KOTAK BANK,current,ACC-1005,50500,tirupati,GMAIL.COM,TIR

In [14]:
df['account_number'] = df['account_number'].str.replace('ACC-', '', regex=False)
df

,customer_name,email,bank_name,account_type,account_number,balance,branch_city,domain,branch_code
0,Santhosh Chevuri,SANTHOSH@GMAIL.COM,HDFC BANK,savings,1001,125000,hyderabad,GMAIL.COM,HYD
1,Raju Kumar,RAJU@YAHOO.COM,ICICI BANK,CURRENT,1002,2500,VIJAYAWADA,YAHOO.COM,VIJ
2,Kiran Reddy,KIRAN@GMAIL.COM,AXIS BANK,salary,1003,75000,vizag,GMAIL.COM,VI
3,Suresh Babu,SURESH@OUTLOOK.COM,SBI,SAVINGS,1004,10000,GUNTUR,OUTLOOK.COM,GUN
4,Lakshmi Devi,LAKSHMI@GMAIL.COM,KOTAK BANK,current,1005,50500,tirupati,GMAIL.COM,TIR