<a href="https://colab.research.google.com/github/bharathrockstar813-byte/e-commerce-/blob/main/TASK_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/data cleaing/employee_attendance (1).csv")
df

  employee_name  login_date login_time  working_hours
0          Ravi  2024-02-10   08:45:30              8
1         Priya  2024-03-15   09:10:15              9
2       Karthik  2024-05-20   08:55:45              8
3        Anjali  2024-07-08   09:25:10              7
4        Vikram  2024-11-25   08:30:20              9

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   employee_name  5 non-null      object
 1   login_date     5 non-null      object
 2   login_time     5 non-null      object
 3   working_hours  5 non-null      int64
dtypes: int64(1), object(3)
memory usage: 292.0+ bytes

In [15]:
df['login_date']=pd.to_datetime(df['login_date'])
df['login_time']=pd.to_datetime(df['login_time'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   employee_name  5 non-null      object
 1   login_date     5 non-null      datetime64[ns]
 2   login_time     5 non-null      datetime64[ns]
 3   working_hours  5 non-null      int64
 4   hour           5 non-null      int32
 5   minute         5 non-null      int32
dtypes: datetime64[ns](2), int32(2), int64(1), object(1)
memory usage: 332.0+ bytes

In [ ]:
df["year"]=pf["login_date"].dt.year
df["month"]=df["login_date"].dt.month
df["day"]=df["login_date"].dt.day
df

NameError: name 'pf' is not defined

In [16]:
df['month_name'] = df['login_date'].dt.month_name()
df

,employee_name,login_date,login_time,working_hours,hour,minute,month_name
0,Ravi,2024-02-10,2026-05-30 08:45:30,8,8,45,February
1,Priya,2024-03-15,2026-05-30 09:10:15,9,9,10,March
2,Karthik,2024-05-20,2026-05-30 08:55:45,8,8,55,May
3,Anjali,2024-07-08,2026-05-30 09:25:10,7,9,25,July
4,Vikram,2024-11-25,2026-05-30 08:30:20,9,8,30,November

In [19]:
df['day_name']=df['login_date'].dt.day_name()
df

,employee_name,login_date,login_time,working_hours,hour,minute,month_name,day_name
0,Ravi,2024-02-10,2026-05-30 08:45:30,8,8,45,February,Saturday
1,Priya,2024-03-15,2026-05-30 09:10:15,9,9,10,March,Friday
2,Karthik,2024-05-20,2026-05-30 08:55:45,8,8,55,May,Monday
3,Anjali,2024-07-08,2026-05-30 09:25:10,7,9,25,July,Monday
4,Vikram,2024-11-25,2026-05-30 08:30:20,9,8,30,November,Monday

In [22]:
df['login_time']=pd.to_datetime(df['login_time'], format= '%H:%M:%S')
df["hour"]=df["login_time"].dt.hour
df["minute"]=df["login_time"].dt.minute
df["second"]=df["login_time"].dt.second
df

,employee_name,login_date,login_time,working_hours,hour,minute,month_name,day_name,second
0,Ravi,2024-02-10,2026-05-30 08:45:30,8,8,45,February,Saturday,30
1,Priya,2024-03-15,2026-05-30 09:10:15,9,9,10,March,Friday,15
2,Karthik,2024-05-20,2026-05-30 08:55:45,8,8,55,May,Monday,45
3,Anjali,2024-07-08,2026-05-30 09:25:10,7,9,25,July,Monday,10
4,Vikram,2024-11-25,2026-05-30 08:30:20,9,8,30,November,Monday,20

In [23]:
earliest_date = df['login_date'].min()
print("Earliest Login Date:", earliest_date)

Earliest Login Date: 2024-02-10 00:00:00

In [24]:
latest_date = df['login_date'].max()
print("Latest Login Date:", latest_date)

Latest Login Date: 2024-11-25 00:00:00

In [25]:
max_employee = df.loc[df['working_hours'].idxmax()]

print(max_employee)

employee_name                  Priya
login_date       2024-03-15 00:00:00
login_time       2026-05-30 09:10:15
working_hours                      9
hour                               9
minute                            10
month_name                     March
day_name                      Friday
second                            15
Name: 1, dtype: object